### ISSUE TITLE
请求新增密友朋友圈功能

### ISSUE THREAD

**Issue by Awu1d** [dannyit/WechatChums#10]
最近添加了密友自动屏蔽电话和视频功能，很实用…

希望大大有空新增一个密友自动屏蔽朋友圈密友的相关评论…

例如我发个朋友圈，好友A做了评论…当我将其设置为密友时，那条评论也会自动隐藏

**Comment by dannyit** [comment]
朋友群手动用微信原生屏蔽吧

**Comment by Awu1d** [comment]
原生屏蔽只能屏蔽对方朋友圈，或者不让对方看我的朋友圈，
无法实现仅屏蔽对方对我的评论。

示例：
我将A设置为密友，好友列表以及消息列表中没有A这个人。
但是A在给我的朋友圈评论时，会显示A的评论。

希望得到的效果：
在将A设置为密友后，A在我朋友圈内的全部评论一并进行隐藏，
这个是源生屏蔽中无法实现的效果
源生屏蔽，只能屏蔽A不看我的朋友圈，和不看A的朋友圈。以前的评论仍然在朋友圈内。


望大佬在闲余之时能考虑下，给大佬添麻烦啦。

**Comment by Awu1d** [comment]
> 朋友群手动用微信原生屏蔽吧

原生屏蔽只能屏蔽对方朋友圈，或者不让对方看我的朋友圈，
无法实现仅屏蔽对方对我的评论。

示例：
我将A设置为密友，好友列表以及消息列表中没有A这个人。
但是A在给我的朋友圈评论时，会显示A的评论。

希望得到的效果：
在将A设置为密友后，A在我朋友圈内的全部评论一并进行隐藏，
这个是源生屏蔽中无法实现的效果
源生屏蔽，只能屏蔽A不看我的朋友圈，和不看A的朋友圈。以前的评论仍然在朋友圈内。


望大佬在闲余之时能考虑下，给大佬添麻烦啦。
