### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by nishenge** [dannyit/WechatChums#12]
大佬您好，我在小米mix2上测试您的软件发现了一些bug，现在向您进行反馈
运行环境如下
微信7.0.5google市场版   模块版本当前最新1.1.7     
已安装的模块：  阿里系xposed反检测    核心破解    微x模块   无障碍——Daemon   小鸡炖蘑菇    音量增强器    GG tolls 写轮眼  Qx模块
问题：
无法通过双击左上角微信字样召唤出解锁命令

**Comment by dannyit** [comment]
现在不支持google play版

**Comment by EdisonEDC** [comment]
您好，我的是华为p30pro，在无极阴里下载的微信，为什么还是不能生效呢？麻烦您指点一下
